name: CI Workflow
on: [push]

defaults:
  run:
    shell: bash 

jobs:
  Initiate-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate Pipeline
        run: |
          echo "::group:: Initiate Pipeline Execution"
          whoami
          pwd
          ls -ltr
          echo "::endgroup::"

  Repository-Checkout:
    runs-on: ubuntu-latest
    needs: Initiate-Pipeline
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
  
  Build-Artifact:
    runs-on: ubuntu-latest
    needs: Repository-Checkout
    steps:
      - name: Build Artifact
        run: |
          npm install
          CI=false npm run build
          ls -ltr

  Sonar-Scan:
    runs-on: ubuntu-latest
    needs: Build-Artifact
    steps:
      - name: Sonar Scan
        run: |
          npm run sonar
