name: CI Workflow
on: [push]

defaults:
  run:
    shell: bash 

jobs:
  CI-Pipeline-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate Pipeline
        run: |
          echo "::group:: Initiate Pipeline Execution"
          whoami
          pwd
          ls -ltr
          echo "::endgroup::"
      
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Build Artifact
        run: |
          echo "::group:: Build Artifact Execution"
          npm install
          CI=false npm run build
          ls -ltr
          echo "::endgroup::"

      - name: Sonar Scan
        run: |
          echo "::group:: Sonar Scan Execution"
          npm run sonar
          echo "::endgroup::"
