name: CI Workflow
on: [push]

jobs:
    CI-Execution:
        runs-on: ubuntu-latest
        steps:
            - name: Initiate Pipeline
              run: |
                echo "::group:: Initiate Pipeline"
                whoami
                pwd
                ls -la
                echo "::endgroup::"

            - name: Checkout Repository Code
              uses: actions/checkout@v3

            - name: Build Artifact
              run: |
                echo "::group:: Build Artifact"
                npm install
                npm run build
                ls -la
                echo "::endgroup::"
