name: CI Workflow
on: [push]

defaults:
  run:
    shell: bash 

jobs:
  CI-Pipeline-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate Pipeline
        run: |
          whoami
          pwd
          ls -ltr
      
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Build Artifact
        run: |
          npm install
          CI=false npm run build
          ls -ltr

      - name: Sonar Scan 
        env:
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
          SONARQUBE_USERNAME: ${{ secrets.SONARQUBE_USERNAME }}
          SONARQUBE_PASSWORD: ${{ secrets.SONARQUBE_PASSWORD }}
        run: |
          npm run sonar -- --sonar.host.url=${{ secrets.SONARQUBE_URL }} \
                          --sonar.login=${{ secrets.SONARQUBE_USERNAME }} \
                          --sonar.password=${{ secrets.SONARQUBE_PASSWORD }}

